apiVersion: v1
kind: Service
metadata:
  name: {{ include "golang-mathapp-chart.fullname" . }}
spec:
  selector:
    app: {{ include "golang-mathapp-chart.name" . }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8010
  type: {{ .Values.service.type }}

